[project]
name = "fixpricescraper"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.12"
dependencies = [
    "requests>=2.32.3",
    "scrapy>=2.12.0",
    "scrapy-user-agents>=0.1.1",
]
